### ISSUE TITLE
connect deviceMode 不生效

### ISSUE THREAD

**Issue by wwb1117** [shimohq/shimo-js-sdk#50]
![image](https://user-images.githubusercontent.com/38465242/227881375-41da700f-508e-423f-8a77-b330da4209e1.png)
![image](https://user-images.githubusercontent.com/38465242/227881501-0d370006-e7e4-4052-8cea-4617cfb68c1f.png)

**Comment by chrisyip** [comment]
https://github.com/shimohq/shimo-js-sdk/blob/master/docs/interfaces/ConnectOptions.md#devicemode

文档有说明，特殊版本的才支持指定，一般走 user-agent 判断。
