### ISSUE TITLE
TypeError: Symbol(Symbol.toStringTag) not a string

### ISSUE THREAD

**Issue by wwb1117** [shimohq/shimo-js-sdk#51]
![image](https://user-images.githubusercontent.com/38465242/227896968-6b28575e-5334-4731-ad7d-0fc48da1f85b.png)
![image](https://user-images.githubusercontent.com/38465242/227897022-26765b99-8e35-4174-906d-63759d55aa10.png)

**Comment by chrisyip** [comment]
给一下具体的 stack trace 和可复现代码

**Comment by wwb1117** [comment]
connect 返回的sdk对象， 不能用Vue data 里面的变量赋值 。因为不能被Vue遍历observe。可以用最外层的变量赋值。
